### ISSUE TITLE
Music filters

### ISSUE THREAD

**Issue by muralianand12345** [Blackfort-Hosting/magmastream#112]
How do I apply filters to my music?

`{
  Manager: [Getter],
  Node: [Getter],
  Player: [Getter],
  Queue: [Getter],
  TrackUtils: [Getter],
  Structure: [Getter],
  Plugin: [Getter]
}`

**Comment by Vexify4103** [comment]
Hello, there are two basic options for you.

1. You can use the given filters from magmastream. Like this for example: `player.filters.bassBoost()` and to clear filters: `player.filters.clearFilters();`
2. You can extend the player class and add your own filters with set band settings etc. example: https://sourceb.in/wRWcnKPIIn
and then call something like this for example: `player.setBassboost(value);`

A list of pre-given filters can be found here: https://docs.blackforthosting.com/classes/filters
