### ISSUE TITLE
New event: playerStateUpdate

### ISSUE THREAD

**Issue by Vexify4103** [Blackfort-Hosting/magmastream#16]
**Event Details:**

The "playerStateUpdate" event would be triggered whenever there is a significant state change in the player. Specifically, it should respond with the following information:

1. Player: The instance of the player that experienced the state change.
2. State Update: A descriptive object containing details about the specific change that occurred. This could include information about pausing, resuming, and loop-mode changes.

**Supported State Changes:**

The event should cover the following player state updates:

- Pause/Resume: When the player gets paused or resumed during music playback.
- Loop Mode: When the loop-mode of the player changes from "track" to "queue" or "off" (and vice versa).

**Use Case:**

The primary purpose of this event is to help developers handle potential timeout issues in their Discord bots. At times, due to external factors, the bot's timeout duration may be shorter than the duration of the track playing through the player. This can result in the player getting destroyed while it is actively playing music, leading to an inconsistent and unpleasant user experience.

By having access to the "playerStateUpdate" event, developers can implement custom timeout handling strategies. For example, if the bot's timeout is about to expire, they can check if the player is actively playing and, if so, extend the timeout or take appropriate actions to prevent the player from being destroyed prematurely.

**Benefits:**

Adding the "playerStateUpdate" event would offer the following benefits:

1. Improved Bot Reliability: Developers can implement better timeout management to avoid issues with active music playback.
2. Enhanced Customization: The event allows for more sophisticated state-change handling tailored to specific bot requirements.
3. Real-time Monitoring: Developers can have insights into player state changes as they occur, enabling them to respond accordingly.

**Comment by SxMAbel** [comment]
"State Update: A descriptive object containing details about the specific change that occurred. This could include information about pausing, resuming, and loop-mode changes." 

In the `Player` you can check for what has been changed instead of having duplicates, example: someone pauses the player, the `playerStateUpdate` will fire, and you can access what type of change you are looking for, in this example, "pause" so you can do `player.paused` to get either `true` or `false`.
