### ISSUE TITLE
Add a custom store with the tracks

### ISSUE THREAD

**Issue by BloomyInDev** [Blackfort-Hosting/magmastream#190]
**Is your feature request related to a problem? Please describe.**
I've created a music bot with your library but i encounter a little problem...
I can't store if a music is a radio from us or if it one from the user
I've managed to get around this by storing in `Track.requester` an object with what i've needed (radio from us or not and who asked for the music)
But with the last update, you've added type to `Track.requester` (great !)

**Describe the Solution You'd Like**
Could you add a custom field in the `Track` interface to store additional data (whatever we want so with `unknown`

**Describe Alternatives You've Considered**
For now i force things by overriding this field and "it works enough"

**Additional Context**
Nothing to add i think

**Comment by SxMAbel** [comment]
> **Is your feature request related to a problem? Please describe.** I've created a music bot with your library but i encounter a little problem... I can't store if a music is a radio from us or if it one from the user I've managed to get around this by storing in `Track.requester` an object with what i've needed (radio from us or not and who asked for the music) But with the last update, you've added type to `Track.requester` (great !)
> 
> **Describe the Solution You'd Like** Could you add a custom field in the `Track` interface to store additional data (whatever we want so with `unknown`
> 
> **Describe Alternatives You've Considered** For now i force things by overriding this field and "it works enough"
> 
> **Additional Context** Nothing to add i think

https://www.npmjs.com/package/magmastream/v/2.5.3

**Comment by BloomyInDev** [comment]
Thank you !
