### ISSUE TITLE
Add spotify default search

### ISSUE THREAD

**Issue by Yanishamburger** [Blackfort-Hosting/magmastream#225]
Hello, I came to ask for a new addition that you could put.

Add to music by default which could come from Spotify, I don't know if it's possible for you, thank you for your attention, have a good day.

Sincerely

**Comment by SxMAbel** [comment]
Please open a forum on discord

**Comment by Yanishamburger** [comment]
Hello, can you tell me or create a forum because I don't quite understand the answer?

**Comment by SxMAbel** [comment]
discord.gg/HV59Z3zEjt
