### ISSUE TITLE
Clearfilters not working

### ISSUE THREAD

**Issue by Johna21** [Blackfort-Hosting/magmastream#26]
NodeJs Version: 20.4.0
Lavalink Version: 4.0.0-beta.2
Magmastream NPM Package Version: 2.2.1

**Describe the Bug**
Whenever I start a filter for ex: Bassboost, it works perfectly but when I do .clearFilters(), nothing happens. I have checked for errors etc and I had no errors.

**To Reproduce**

1. Play the music
2. Turn on the filter
3. Wait for it to turn on
4. Using clearFilters will never turn it off now

**Expected Behavior**
It should clear all filters using clearFilters but it is not working and expected.

**Screenshots**
N/A

**Additional Context**
N/A

**Comment by SxMAbel** [comment]
Just released an update to fix your issue. 

`npm install magmastream@2.2.2`

**Comment by szymonwilczek** [comment]
I cannot see the fix, still the clearFliters() ain't changing a thing.

**Comment by SxMAbel** [comment]
> I cannot see the fix, still the clearFliters() ain't changing a thing.

What version do you have installed?

**Comment by szymonwilczek** [comment]
2.3.1, the newest i guess

**Comment by SxMAbel** [comment]
> 2.3.1, the newest i guess

Can you provide code?

**Comment by szymonwilczek** [comment]
sure, here you go:

```js
if (player.filters.getFilterStatus("eightD")) {
      player.filters.clearFilters();
      return client.sendMessage(
        message.channel,
        `Turned off`
      );
    } else {
      player.filters.eightD();
      return client.sendMessage(
        message.channel,
        `Turned on`
      );
    }
```

**Comment by SxMAbel** [comment]
> ```js
> player.filters.clearFilters()
> ```

`player.filters.clearFilters()` -> `await player.filters.clearFilters()`

**Comment by szymonwilczek** [comment]
Oh jesus, I just saw in the documentation that it returns Promise, and I did not await it.... Thanks..

**Comment by SxMAbel** [comment]
> Oh jesus, I just saw in the documentation that it returns Promise, and I did not await it.... Thanks..

You're Welcome
