### ISSUE TITLE
Load Balancing Properly

### ISSUE THREAD

**Issue by Nansess** [Blackfort-Hosting/magmastream#89]
Problem:
The current load-balancing system relies on CPU usage, neglecting server distribution across nodes and my other nodes in diff regions aren't used

Solution:
Implement load balancing based on server regions. Allow labeling of nodes with regions for management.

**Comment by SxMAbel** [comment]
> Problem: The current load-balancing system relies on CPU usage, neglecting server distribution across nodes and my other nodes in diff regions aren't used
> 
> Solution: Implement load balancing based on server regions. Allow labeling of nodes with regions for management.

https://github.com/Blackfort-Hosting/magmastream/pull/99
