### ISSUE TITLE
Spotify songs

### ISSUE THREAD

**Issue by muralianand12345** [Blackfort-Hosting/magmastream#95]
**Your Question**
How to play Spotify?

**Additional Context**
`client.manager = new Manager({
    nodes: nodes,
    defaultSearchPlatform: 'spsearch',
    send: (id, payload) => {
        const guild = client.guilds.cache.get(id);
        if (guild) guild.shard.send(payload);
    }
});`

**Comment by muralianand12345** [comment]
Just figured out!
Need to add this in Manager.js
```
Manager.DEFAULT_SOURCES = {
    // youtubemusic
    "youtube music": "ytmsearch",
    "ytmsearch": "ytmsearch",
    "ytm": "ytmsearch",
    // youtube
    "youtube": "ytsearch",
    "yt": "ytsearch",
    "ytsearch": "ytsearch",
    // soundcloud
    "soundcloud": "scsearch",
    "scsearch": "scsearch",
    "sc": "scsearch",
    // apple music
    "amsearch": "amsearch",
    "am": "amsearch",
    // spotify 
    "spsearch": "spsearch",
    "sp": "spsearch",
    "sprec": "sprec",
    "spsuggestion": "sprec",
    // deezer
    "dz": "dzsearch",
    "deezer": "dzsearch",
    "ds": "dzsearch",
    "dzsearch": "dzsearch",
    "dzisrc": "dzisrc",
};
```

**Comment by Vexify4103** [comment]
Or just use lavascr plugin for your lavalink? (:

**Comment by SxMAbel** [comment]
It is recommended to install the lavasrc plugin on your lavalink server.

**Comment by muralianand12345** [comment]
I've installed those but not working without those
